baseURL = "https://xiegerts.com/"
languageCode = "en-us"
title = "xiegerts"
theme ="hugo-theme-basic"
enableEmoji = true


GoogleAnalytics = "UA-134038089-1"
copyright = "Â© 2020 Copyright Stephen Siegert (<a href='https://twitter.com/siegerts' class='link black-40'>@siegerts</a>). All rights reserved."


[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[params]
  titleEmoji = ":coffee: :dog:"
  twitter = "siegerts"
  description = "Thoughts, comments, and technology commentary."

[Permalinks]
  blog = "blog/:slug"

# links
[[params.menu]]
  name = "blog"
  url = "post/"

[[params.menu]]
  name = "series"
  url = "series/"

[[params.menu]]
  name = "about"
  url = "about/"


[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true
    respectDoNotTrack = true
    useSessionStorage = true
  [privacy.twitter]
    enableDNT = true
  [privacy.youtube]
    privacyEnhanced = true